# Generated by Django 4.2.2 on 2023-06-15 04:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driv_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique='True')),
                ('email', models.EmailField(max_length=254, unique='True')),
                ('password', models.CharField(max_length=128)),
                ('driv_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('driv_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique='True')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient', models.CharField(max_length=20)),
                ('pick_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('pick_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('contact', models.CharField(max_length=10)),
                ('hospital_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('hospital_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.genuser')),
            ],
        ),
        migrations.CreateModel(
            name='pending_req',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('pending_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.driv_user')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.request')),
            ],
        ),
    ]
