# Generated by Django 4.2.2 on 2023-07-02 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient', models.CharField(max_length=20)),
                ('pickLatitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('pickLongitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('contact', models.CharField(max_length=10)),
                ('hospitalLatitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('hospitalLongitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Completed_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.request')),
            ],
        ),
        migrations.CreateModel(
            name='Accepted_req',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('pending_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.request')),
            ],
        ),
    ]
