# Generated by Django 4.2.2 on 2023-06-15 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '0002_alter_pending_req_driver_alter_request_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pending_req',
            new_name='Accepted_req',
        ),
    ]
