# Generated by Django 4.2.2 on 2023-06-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_rename_pending_req_accepted_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
