# Generated by Django 4.2.2 on 2023-06-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_completed_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_trip',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
